# Auto-labeling configuration based on file changes

# Area labels
'area: bridge':
  - changed-files:
    - any-glob-to-any-file: 'src/mcp_foxxy_bridge/bridge_server.py'
  - changed-files:
    - any-glob-to-any-file: 'src/mcp_foxxy_bridge/proxy_server.py'
  - changed-files:
    - any-glob-to-any-file: 'src/mcp_foxxy_bridge/server_manager.py'

'area: server':
  - changed-files:
    - any-glob-to-any-file: 'src/mcp_foxxy_bridge/mcp_server.py'
  - changed-files:
    - any-glob-to-any-file: 'src/mcp_foxxy_bridge/sse_client.py'
  - changed-files:
    - any-glob-to-any-file: 'src/mcp_foxxy_bridge/streamablehttp_client.py'

'area: config':
  - changed-files:
    - any-glob-to-any-file: ['src/mcp_foxxy_bridge/config_loader.py', 'docs/examples/**/*', 'config.json', '**/*config*.json']

'area: docker':
  - changed-files:
    - any-glob-to-any-file: ['Dockerfile', 'docker-compose.yml', '.dockerignore']

'area: docs':
  - changed-files:
    - any-glob-to-any-file: ['docs/**/*', 'README.md', 'CONTRIBUTING.md', 'CHANGELOG.md']

'area: tests':
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*', 'test_*.py', '*_test.py']

'area: ci/cd':
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*', '.github/labels.yml', '.github/labeler.yml', '.releaserc.json', 'codecov.yml']

# Type labels based on file patterns
'type: documentation':
  - changed-files:
    - any-glob-to-any-file: ['docs/**/*', 'README.md', 'CONTRIBUTING.md', '**/*.md']

'type: test':
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*', 'test_*.py', '*_test.py']

'type: ci':
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*', '.github/labels.yml', '.github/labeler.yml']

'type: build':
  - changed-files:
    - any-glob-to-any-file: ['pyproject.toml', 'Dockerfile', 'docker-compose.yml', '.releaserc.json', 'uv.lock', 'poetry.lock']

'type: chore':
  - changed-files:
    - any-glob-to-any-file: ['.gitignore', '.gitmessage', 'VERSION', '.env*']

# Dependencies
'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['pyproject.toml', 'uv.lock', 'poetry.lock', 'package.json', 'package-lock.json']