# Auto-labeling configuration based on file changes

# Area labels
"area: bridge":
  - 'src/mcp_foxxy_bridge/bridge_server.py'
  - 'src/mcp_foxxy_bridge/proxy_server.py'
  - 'src/mcp_foxxy_bridge/server_manager.py'

"area: server":
  - 'src/mcp_foxxy_bridge/mcp_server.py'
  - 'src/mcp_foxxy_bridge/sse_client.py'
  - 'src/mcp_foxxy_bridge/streamablehttp_client.py'

"area: config":
  - 'src/mcp_foxxy_bridge/config_loader.py'
  - 'docs/examples/**/*'
  - 'config.json'
  - '**/*config*.json'

"area: docker":
  - 'Dockerfile'
  - 'docker-compose.yml'
  - '.dockerignore'

"area: docs":
  - 'docs/**/*'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'CHANGELOG.md'

"area: tests":
  - 'tests/**/*'
  - 'test_*.py'
  - '*_test.py'

"area: ci/cd":
  - '.github/workflows/**/*'
  - '.github/labels.yml'
  - '.github/labeler.yml'
  - '.releaserc.json'
  - 'codecov.yml'

# Type labels based on file patterns
"type: documentation":
  - 'docs/**/*'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - '**/*.md'

"type: test":
  - 'tests/**/*'
  - 'test_*.py'
  - '*_test.py'

"type: ci":
  - '.github/workflows/**/*'
  - '.github/labels.yml'
  - '.github/labeler.yml'

"type: build":
  - 'pyproject.toml'
  - 'Dockerfile'
  - 'docker-compose.yml'
  - '.releaserc.json'
  - 'uv.lock'
  - 'poetry.lock'

"type: chore":
  - '.gitignore'
  - '.gitmessage'
  - 'VERSION'
  - '.env*'

# Dependencies
"dependencies":
  - 'pyproject.toml'
  - 'uv.lock'
  - 'poetry.lock'
  - 'package.json'
  - 'package-lock.json'